# Generated by Django 3.2.8 on 2021-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0002_auto_20211006_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='api_url',
            field=models.URLField(default='http://127.0.0.1:8000/api/video/<built-in function id>'),
        ),
    ]
