# Generated by Django 3.2.8 on 2021-10-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0003_page_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='api_url',
            field=models.CharField(default='http://127.0.0.1:8000/api/video/<built-in function id>', max_length=120),
        ),
    ]
