# Generated by Django 3.2.8 on 2021-10-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0004_alter_page_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='api_url',
            field=models.CharField(default='http://127.0.0.1:8000/api/video/<django.db.models.fields.IntegerField>', max_length=120),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
