# Generated by Django 3.2.8 on 2021-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0005_auto_20211007_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='api_url',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='http://127.0.0.1:8000/api/video/<built-in function id>/', max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
