# Generated by Django 3.2.8 on 2021-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_page', '0008_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default='http://127.0.0.1:8000/api/video/<property object at 0x0000021C92695C20>/', max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
